name: Daily Notepad Update

on:
  workflow_dispatch:   # â† Enables manual "Run workflow" button
  schedule:
    - cron: '18 26 * * *'

jobs:
  update-notepad:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate 4-digit random number and update notepad.txt
        run: |
          RANDOM_NUM=$((1000 + RANDOM % 9000))
          echo "Random 4-digit update: $RANDOM_NUM on $(date -u)" >> notepad.txt

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add notepad.txt
          git commit -m "Daily update with random number: $(date -u)" || echo "No changes to commit"
          git push
