name: Daily Notepad Multi-Update

on:
  schedule:
    - cron: '04 22 * * *'  # Runs once per day at 6:00 UTC (choose your base time)
  workflow_dispatch:        # Allows manual runs

jobs:
  update-notepad:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate and commit 4–10 random numbers throughout the day
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

          LOOP_COUNT=$((4 + RANDOM % 7))  # 4 to 10 times

          for ((i=1; i<=LOOP_COUNT; i++)); do
            RANDOM_NUM=$((1000 + RANDOM % 9000))
            echo "Random 4-digit update: $RANDOM_NUM on $(date -u)" >> notepad.txt

            git add notepad.txt
            git commit -m "Update $i of $LOOP_COUNT: $RANDOM_NUM at $(date -u)" || echo "No changes"
            git push

            # Random sleep time: 10 to 60 minutes
            SLEEP_MINUTES=$((10 + RANDOM % 50))
            echo "Sleeping for $SLEEP_MINUTES minutes..."
            sleep "${SLEEP_MINUTES}m"
          done
