name: Daily Notepad Update

on:
  schedule:
    - cron: '43 21 * * *'  # Every day at 21:18 UTC
  workflow_dispatch:

jobs:
  update-notepad:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Append random 4-digit number to notepad.txt
        run: |
          RANDOM_NUM=$((1000 + RANDOM % 9000))
          echo "Random number: $RANDOM_NUM on $(date -u)" >> notepad.txt

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add notepad.txt
          git commit -m "Auto-update notepad with random number" || echo "No changes"
          git push
